/* ---------------------------------------------------------------------------
 * THE SUNRISE
 *
 * The app's entire colour is a function of one number: how far through the
 * session you are. It walks an actual dawn, from astronomical twilight to the
 * sun clearing the horizon.
 *
 * Two decisions worth knowing about:
 *
 * 1. Everything is OKLCH, not HSL. HSL's "lightness" is not perceived
 *    lightness — at a fixed L, yellow reads far brighter than indigo, so an
 *    HSL ramp visibly surges and dips in brightness on the way round the
 *    wheel, and goes muddy through the magentas. OKLCH is perceptually
 *    uniform, so a straight line through it looks like a straight line.
 *
 * 2. The stops are hand-picked from the phases of a real dawn rather than
 *    generated by a formula. A formula gave an even ramp; it did not give a
 *    sunrise. Lightness climbs monotonically (0.63 → 0.82) because dawn gets
 *    brighter, and chroma peaks in the middle, where the sky is genuinely at
 *    its most saturated, then eases back into the golden light.
 * ------------------------------------------------------------------------- */

export interface Oklch {
  l: number;
  c: number;
  h: number;
}

/** Hues are deliberately left unwrapped (they run past 360) so interpolation
 *  between neighbours is a plain lerp with no shortest-path special case. CSS
 *  treats hue as an angle and wraps it itself. */
const STOPS: readonly (Oklch & { t: number })[] = [
  { t: 0.0, l: 0.63, c: 0.145, h: 274 }, // astronomical twilight — deep indigo
  { t: 0.26, l: 0.665, c: 0.168, h: 309 }, // nautical — violet lifts off the horizon
  { t: 0.5, l: 0.705, c: 0.176, h: 350 }, // civil — the rose band, sky at peak chroma
  { t: 0.74, l: 0.762, c: 0.166, h: 32 + 360 }, // first light — coral
  { t: 1.0, l: 0.822, c: 0.152, h: 74 + 360 }, // sunrise — gold
];

const clamp01 = (n: number) => Math.min(1, Math.max(0, n));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
/** Ease within each segment so the colour eases into each phase instead of
 *  changing at a constant rate and hitting the stops as corners. */
const smooth = (t: number) => t * t * (3 - 2 * t);

export function sunriseAt(t: number): Oklch {
  const p = clamp01(t);
  for (let i = 1; i < STOPS.length; i++) {
    const b = STOPS[i];
    if (p <= b.t) {
      const a = STOPS[i - 1];
      const k = smooth((p - a.t) / (b.t - a.t));
      return { l: lerp(a.l, b.l, k), c: lerp(a.c, b.c, k), h: lerp(a.h, b.h, k) };
    }
  }
  const last = STOPS[STOPS.length - 1];
  return { l: last.l, c: last.c, h: last.h };
}

export function oklchString({ l, c, h }: Oklch, alpha = 1): string {
  const base = `${l.toFixed(4)} ${c.toFixed(4)} ${h.toFixed(2)}`;
  return alpha === 1 ? `oklch(${base})` : `oklch(${base} / ${alpha})`;
}

/** Writes the live accent onto :root. The three channels are registered with
 *  @property in index.css, so the browser interpolates them — advancing a step
 *  drifts the whole app's colour rather than snapping it. Because they're
 *  OKLCH channels, that interpolation is perceptually even. */
export function applySunrise(t: number): void {
  const { l, c, h } = sunriseAt(t);
  const root = document.documentElement.style;
  root.setProperty("--accent-l", l.toFixed(4));
  root.setProperty("--accent-c", c.toFixed(4));
  root.setProperty("--accent-h", h.toFixed(2));
  root.setProperty("--sun", clamp01(t).toFixed(3));
}

/* --- OKLCH → hex ----------------------------------------------------------
 * Needed only for canvas-confetti, which takes concrete colour strings and
 * can't read CSS custom properties. */

export function oklchToHex({ l, c, h }: Oklch): string {
  const rad = (h * Math.PI) / 180;
  const a = c * Math.cos(rad);
  const bb = c * Math.sin(rad);

  const l_ = l + 0.3963377774 * a + 0.2158037573 * bb;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * bb;
  const s_ = l - 0.0894841775 * a - 1.291485548 * bb;

  const L = l_ * l_ * l_;
  const M = m_ * m_ * m_;
  const S = s_ * s_ * s_;

  const lin = [
    4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S,
    -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S,
    -0.0041960863 * L - 0.7034186147 * M + 1.707614701 * S,
  ];

  const toByte = (v: number) => {
    const srgb = v <= 0.0031308 ? 12.92 * v : 1.055 * Math.pow(v, 1 / 2.4) - 0.055;
    return Math.round(clamp01(srgb) * 255)
      .toString(16)
      .padStart(2, "0");
  };

  return `#${lin.map(toByte).join("")}`;
}

/** Progress value used outside a workout. Home/History/Guide sit in the blue
 *  hour just before dawn; the Summary screen is full sunrise, since you've
 *  finished. */
export const IDLE_PROGRESS = 0.1;
export const DONE_PROGRESS = 1;
