#!/usr/bin/env python3
"""Mechanical checks on the study deck, plus a coverage ledger.

    python3 ios/Tools/check-deck.py            # check, print a report
    python3 ios/Tools/check-deck.py --ledger   # also rewrite plans/007-covered.md

Written because `plans/007` is being filled by a series of cold agents, one
group of 20 at a time, and every group's report has to be verified rather than
believed. The acceptance suite already asserts id uniqueness, the `?` rule and
question well-formedness; this adds the things a test cannot see — the answer
length band, em-dashes, correct-index clustering, and which pre-existing cards
an agent changed when it said it changed none.
"""
import json
import pathlib
import sys
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parents[2]
DECK = ROOT / "ios/Morning/Resources/Content/cards.json"
LEDGER = ROOT / "plans/007-covered.md"

BAND = (190, 290)

cards = json.loads(DECK.read_text())["cards"]
questions = [c for c in cards if "options" in c]
fail = []

ids = [c["id"] for c in cards]
if dupes := [i for i, n in Counter(ids).items() if n > 1]:
    fail.append(f"duplicate ids: {dupes}")

if bad := [c["id"] for c in cards if not c["q"].strip().endswith("?")]:
    fail.append(f"q not phrased as a question: {bad}")

if bad := [c["id"] for c in questions
           if len(c.get("options", [])) != 4 or not 0 <= c.get("correct", -1) <= 3]:
    fail.append(f"malformed questions (degrade to factoids): {bad}")

if over := [(c["id"], len(c["a"])) for c in cards if len(c["a"]) > BAND[1]]:
    fail.append(f"answers over {BAND[1]} chars: {over}")

# Em-dash only. En-dashes in numeric ranges are correct typography and four of
# them are Eden's own; see plans/007 "Standing decisions".
if em := [c["id"] for c in cards if "—" in c["q"] + c["a"] + " ".join(c.get("options", []))]:
    fail.append(f"em-dashes: {em}")

print(f"cards        {len(cards)}   {dict(Counter(c['subject'] for c in cards))}")
print(f"questions    {len(questions)}   correct-index spread {dict(sorted(Counter(c['correct'] for c in questions).items()))}")
lengths = [len(c["a"]) for c in cards]
print(f"answer chars {min(lengths)}-{max(lengths)}  (band {BAND[0]}-{BAND[1]})")

if LEDGER.parent.exists() and "--ledger" in sys.argv:
    lines = [
        "# 007 — what the deck already covers",
        "",
        "**Generated by `ios/Tools/check-deck.py --ledger`. Do not edit by hand.**",
        "",
        "Every card in the deck, so a group does not re-teach what an earlier one",
        "already did. If a card you are about to write is already here, write a",
        "different one.",
        "",
        "**Read the ANSWERS, not only the questions.** This file listed stems",
        "alone until group five, and group five reported the consequence: three",
        "cards it wanted to write were unwritable because an existing card had",
        "already spent their mechanism *inside its answer*, as a contrast clause.",
        "A stem tells you what a card asks; only the answer tells you what it",
        "teaches, and teaching the same thing twice is the duplication that",
        "matters. The deck draws without replacement, so a near-duplicate costs",
        "him a card he has not met.",
        "",
    ]
    for subject in ("wine", "tea"):
        subset = [c for c in cards if c["subject"] == subject]
        lines += [f"## {subject} ({len(subset)})", ""]
        for topic in sorted({c["topic"] for c in subset}):
            lines.append(f"### {topic}")
            lines.append("")
            for c in [x for x in subset if x["topic"] == topic]:
                kind = "Q" if "options" in c else "·"
                lines.append(f"`{kind}` **{c['q']}**")
                lines.append(f"  {c['a']}")
                lines.append("")
    LEDGER.write_text("\n".join(lines))
    print(f"ledger       {LEDGER.relative_to(ROOT)}")

# ---------------------------------------------------------------------------
# ADVISORY: vocabulary spent in a stem or an option without a gloss.
#
# The teach-the-word rule is the deck's most important and the only one no test
# can see. Three groups running, every agent has caught violations in its own
# draft by re-reading all twenty cards by hand, and every violation was
# invisible to the mechanical checks above.
#
# This does not replace the re-read. It aims it: a term is flagged when it is
# rare in the deck (so it is not established vocabulary), appears in the part of
# a card read FIRST (the stem or an option, where a reader who lacks it cannot
# get past), and carries no gloss clause beside it.
#
# False positives are expected and are cheap — a place name in a stem is usually
# fine. A false NEGATIVE is what costs the reader a card, so the net is cast
# wide. Advisory only: it never fails the run.
# ---------------------------------------------------------------------------
import re

def gloss_follows(text: str, term: str) -> bool:
    """A gloss arrives in the same breath: `term, the thing it means`."""
    for m in re.finditer(re.escape(term), text):
        after = text[m.end():m.end() + 70]
        if re.match(r"""\s*[,:(]\s*[a-z]""", after):
            return True
    return False

def candidates(parts: list[str], ordinary: set[str]) -> set[str]:
    """Jargon-shaped tokens. Each part is split on its own, so the first word of
    an option is never mistaken for a capitalised term mid-sentence."""
    found = set()
    for part in parts:
        for sentence in re.split(r"(?<=[.?!])\s+", part):
            tokens = re.findall(r"[A-Za-z\u00C0-\u024F][\w\u00C0-\u024F'-]+", sentence)
            for index, token in enumerate(tokens):
                # A word the deck also writes in lowercase is ordinary English
                # that happens to start a phrase, not a term being spent.
                if token.lower() in ordinary:
                    continue
                if any(ord(ch) > 127 for ch in token):
                    found.add(token)
                elif token.isupper() and 2 <= len(token) <= 5:
                    found.add(token)
                elif index > 0 and token[0].isupper():
                    found.add(token)
    return found

corpus = " ".join(c["q"] + " " + c["a"] + " " + " ".join(c.get("options", [])) for c in cards)
ordinary = {w for w in re.findall(r"[a-z\u00DF-\u024F][\w'-]+", corpus)}
advisories = []
for card in cards:
    parts = [card["q"], *card.get("options", [])]
    read_first = " ".join(parts)
    whole = read_first + " " + card["a"]
    for term in candidates(parts, ordinary):
        # Established vocabulary: the deck uses it in more than one card.
        if corpus.count(term) > 2:
            continue
        # Some card asks what it is, so the deck teaches it outright.
        if any(term in c["q"] for c in cards if c["id"] != card["id"]):
            continue
        # The card's own topic is printed on its masthead, so the word is
        # already labelled before the question is read.
        if term.lower() in card["topic"].lower():
            continue
        # The card EXISTS to define this term: it is named in the stem and
        # explained in the answer. Group four's advisory flagged `FTGFOP`,
        # `Costa`, `Entre` and `Andes` — every one of them the subject of the
        # card that named it, which is the opposite of the failure being hunted.
        if term in card["q"] and term in card["a"]:
            continue
        if gloss_follows(whole, term):
            continue
        advisories.append((card["id"], term))

if advisories:
    print(f"\nADVISORY  {len(advisories)} term(s) spent in a stem or option with no gloss nearby.")
    print("          Re-read these by hand. Many will be fine; the rule needs judgement.")
    for card_id, term in sorted(advisories):
        print(f"  {card_id:<26} {term}")

# ---------------------------------------------------------------------------
# ADVISORY: a name carried with nothing to say where, or what, it is.
#
# Eden found this one himself, on a card opening "Biluochun is a tiny spiral
# green tea from the hills above Lake Tai". Lake Tai is real and load-bearing
# and the card never said it is in Jiangsu. He found it again on "You buy Da
# Hong Pao in a Wuyi shop", where he knew neither the tea nor the mountain.
#
# The rule the deck now holds to: A CARD MAY ASSUME ONLY WHAT ITS TOPIC LABEL
# PLUS ITS OWN STEM SUPPLY. The topic prints on the card's masthead, so AUSTRALIA
# over a Coonawarra card is enough. WUYI over a Da Hong Pao card is not, because
# the label is precisely the thing the reader has not got.
#
# So: flag a card carrying a rare capitalised name and NO locator anywhere — no
# country, no province, none of the seven regions `plans/008` says he holds.
# Grape names and people come back too, which is fine: the only question to put
# to each hit is "would he know where, or what, this is". Advisory, never fails.
# ---------------------------------------------------------------------------
LOCATORS = re.compile(
    r"\b(China|Chinese|Japan|Japanese|Taiwan|Taiwanese|India|Indian|Sri Lanka|Ceylon|Korea|Vietnam"
    r"|Myanmar|Nepal|Kenya|Turkey|Tibet|Tibetan|France|French|Italy|Italian|Spain|Spanish|Portugal"
    r"|Portuguese|Germany|German|Austria|Austrian|Greece|Greek|Hungary|Hungarian|Australia|Australian"
    r"|New Zealand|South Africa|Cape|Chile|Chilean|Argentin\w*|California|Oregon|Washington|New York"
    r"|Fujian|Yunnan|Zhejiang|Jiangsu|Anhui|Hunan|Guangxi|Guangdong|Hubei|Sichuan|Xishuangbanna"
    r"|Bordeaux|Burgundy|Champagne|Rioja|Chianti|Mosel|Napa|Tuscan\w*|Piedmont|Veneto|Verona|Campania"
    r"|Catalonia|Barcelona|Castilian|Andalusian|Rhône|Rhone|Loire|Douro|Médoc|Medoc|Alsace"
    r"|Suzhou|Kyoto|province|prefecture|county|island|coastal|plateau|Atlantic|Pacific|Mediterranean"
    r"|Adriatic|Andes|Alpine)\b",
    re.I,
)

# A month is not a place, and an acronym is the other advisory's business.
NOT_A_PLACE = {
    "january", "february", "march", "april", "may", "june", "july",
    "august", "september", "october", "november", "december",
}

unplaced = []
for card in cards:
    parts = [card["q"], card["a"], *card.get("options", [])]
    whole = " ".join(parts)
    if LOCATORS.search(whole) or LOCATORS.search(card["topic"]):
        continue
    names = set()
    for token in candidates(parts, ordinary):
        bare = token.rstrip("'s").rstrip("'")
        if bare.lower() in NOT_A_PLACE or token.isupper():
            continue
        # Rare enough not to be established deck vocabulary.
        if corpus.count(bare) > 6:
            continue
        # The card exists to define it: named in the stem, explained in the
        # answer. Same carve-out the vocabulary advisory makes, same reason.
        if bare in card["q"] and bare in card["a"]:
            continue
        names.add(bare)
    if names:
        unplaced.append((card["id"], sorted(names)[:4]))

if unplaced:
    print(f"\nADVISORY  {len(unplaced)} card(s) name something with no locator anywhere in the card.")
    print("          Say where it is, or what it is, in the same breath. Judgement required.")
    for card_id, names in sorted(unplaced):
        print(f"  {card_id:<26} {', '.join(names)}")

if fail:
    print("\nFAIL")
    for f in fail:
        print("  " + f)
    sys.exit(1)
print("\nOK")
